version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html

    volumes:
      - .:/var/www/html
    ports: # Add this section
      - "5173:5173"
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dental_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres_data:
