<?php

namespace Database\Factories;

use App\Models\Brand;
use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Model>
 */
class MaterialFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'sku' => $this->faker->unique()->ean8(),
            'name' => $this->faker->words(3, true),
            'description' => $this->faker->sentence(),
            'image' => null, // You can modify this to generate image paths
            'unit' => $this->faker->randomElement(['piece', 'gram', 'ml', 'disk']),
            'price' => $this->faker->randomFloat(2, 10, 1000),
            'stock_quantity' => $this->faker->numberBetween(0, 100),
            'min_stock' => $this->faker->numberBetween(5, 20),
            'barcode' => $this->faker->ean13(),
            'qr_code' => null, // This will be generated by the model event
        ];
    }
}
